server:
    port: 8080
spring:
    application:
        name: cop-map-gateway-service
    config:
        import: "configserver:"
    cloud:
        config:
            discovery:
                enabled: true
                service-id: cop-map-config-service
            fail-fast: true

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_URI:}
    instance:
        instance-id: ${spring.application.name}:${random.value}

logging:
    level:
        org.springframework.cloud.gateway.filter: DEBUG
        org.springframework.cloud.gateway.handler: DEBUG
        org.springframework.web.servlet.DispatcherServlet: DEBUG
        # If using Spring Security, this shows exactly which URL patterns are evaluated:
        org.springframework.security.web.FilterChainProxy: DEBUG